#!/bin/bash
barra=$( echo -e "\e[0;36m======================================================\e[m" ) #55
DIR="/home/VPS-ARG"

function espacio(){
fila=$1
col=$(( ( 55 - $2 )/2 ))
tput cup $fila $col
return
}

function titulo(){
clear
nl=$( echo -n "$1" | wc -m )
echo "$barra"
espacio 1 $nl
echo "$1"
echo "$barra"
return
}

function aviso2(){
echo "$barra"
tput civis
read -e -p "Enter para continuar" enter
tput cnorm
return
}

function BadVPN(){
titulo "BadVPN"
pid_badvpn=$( netstat -putona | grep badvpn-ud )
#pid_badvpn=$( lsof | grep -w "badvpn" | grep -v grep | awk '{print $1}')
if [[ $pid_badvpn == "" ]]; then
echo -e "Instalando badvpn.."
    if [[ ! -e /bin/badvpn-udpgw ]]; then
	wget -O /bin/badvpn-udpgw https://raw.githubusercontent.com/powermx/badvpn/master/badvpn-udpgw &>/dev/null
	chmod +x /bin/badvpn-udpgw
    fi
screen -dmS badvpn2 /bin/badvpn-udpgw --listen-addr 127.0.0.1:7300 --max-clients 1000 --max-connections-for-client 10
sysctl -w net.core.rmem_max=1000000 &> /dev/null
sysctl -w net.core.rmem_default=1000000 &> /dev/null
sleep 3
tput cuu1 && tput el1
	if [[ "$(ps x | grep badvpn | grep -v grep | awk '{print $1}')" ]]; then
	echo -e "OK - badvpn instalado"
	else
	echo -e "Fail - badvpn no instaldo"
	fi
else
echo -e "Desintalando badvpn.."
sleep 3
kill -9 $(ps x | grep badvpn | grep -v grep | awk '{print $1'}) > /dev/null 2>&1
killall badvpn-udpgw > /dev/null 2>&1
	if [[ ! "$(ps x | grep badvpn | grep -v grep | awk '{print $1}')" ]]; then 
	ctrl=$( cat ${DIR}/controles | grep -v "badvpn" )
	echo "$ctrl" > ${DIR}/controles
	echo -e "\nOk - badvpn desinstalado"
	unset pid_badvpn
	fi
fi
unset pid_badvpn
aviso2
}

BadVPN
exit
