#!/bin/bash

#Direcciones
DIR="/home/VPS-ARG"
aux3="${DIR}/.aux3"
aux4="${DIR}/.aux4"
limitados="${DIR}/limitados"
#Valores
rm -r $aux3 &> /dev/null
rm -r $aux4 &> /dev/null

function desconectar(){
nd=$1
data=( `ps aux | grep -i dropbear | awk '{print $2}'`);

for PID in "${data[@]}"
do
        NUM=`cat /var/log/auth.log | grep -i dropbear | grep -i "Password auth succeeded" | grep "dropbear\[$PID\]" | wc -l`;
        USER=`cat /var/log/auth.log | grep -i dropbear | grep -i "Password auth succeeded" | grep "dropbear\[$PID\]" | awk '{print $10}'`;
        IP=`cat /var/log/auth.log | grep -i dropbear | grep -i "Password auth succeeded" | grep "dropbear\[$PID\]" | awk '{print $12}'`;
        if [ $NUM -eq 1 ]; then
        USER=$( echo -e "${USER:1}" )
        USER=`echo "$USER" | sed 's/.$//g'`
        	if [[ $USER == $nd ]]; then
		pkill $PID
		fi
        fi
done

data=( `ps aux | grep "\[priv\]" | sort -k 72 | awk '{print $2}'`);

for PID in "${data[@]}"
do
        NUM=`cat /var/log/auth.log | grep -i sshd | grep -i "Accepted password for" | grep "sshd\[$PID\]" | wc -l`;
        USER=`cat /var/log/auth.log | grep -i sshd | grep -i "Accepted password for" | grep "sshd\[$PID\]" | awk '{print $9}'`;
        IP=`cat /var/log/auth.log | grep -i sshd | grep -i "Accepted password for" | grep "sshd\[$PID\]" | awk '{print $11}'`;
        if [ $NUM -eq 1 ]; then
        nombre=$( grep -w $USER $DIR/usuarios | awk -F "|" '{print $1}')
                if [[ ! -z $nombre ]]; then
                lim=$( grep -w $USER $DIR/usuarios | awk -F "|" '{print $3}' )
                verif=$( grep -w $nombre $aux3 2> /dev/null )
                        if [[ -z $verif ]]; then
                        echo -e "${nombre}|1|${lim}|$PID" >> $aux3
                        else
                        cont=$( echo -e "$verif" | awk -F "|" '{print $2}' )
                        ((cont++))
                        rem=$( grep -vw $verif $aux3 )
                        echo -e "$rem" > $aux3
                        echo -e "${nombre}|${cont}|${lim}|$PID" >> $aux3
                        fi
                fi
        fi
done

}
